
[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_padding = false
dynamic_title = true
opacity = 0.9

[window.dimensions]
columns = 80
lines = 35

[window.padding]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = true
